import { execFileSync } from "node:child_process";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  rmSync,
  utimesSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { globSync, ZshPatternError, type GlobOptions } from "../src/index.js";
import { canFifo, canSymlink, trySymlink } from "./helpers/platform.js";
import { fixtureLines } from "./helpers/fixture.js";
import globTextsJson from "./fixtures/globs.json" with { type: "json" };

/**
 * Every filename generation pattern that appears anywhere in zsh's test suite,
 * expanded in a fixed tree by the real zsh binary.  The fixture is generated
 * by scripts/harvest-globs.mjs; zsh decides what each glob produces.
 *
 * Each line is "<options>\t<glob>\t<results>", the results separated by \x01.
 */
const SEPARATOR = "";

const lines = fixtureLines(
  fileURLToPath(new URL("./fixtures/harvested-globs.txt", import.meta.url)),
);

const header = new Map(
  lines
    .filter((line) => line.startsWith("#"))
    .map((line) => {
      const tab = line.indexOf("\t");
      return [line.slice(1, tab), line.slice(tab + 1)] as [string, string];
    }),
);
const zshVersion = header.get("zsh") ?? "unknown";
/** The sweep stores indices into this list, for the reason patterns.json exists. */
const globTexts = globTextsJson as string[];
const entries = (key: string) =>
  (header.get(key) ?? "").split(SEPARATOR).filter((name) => name !== "");

/** Option names in bit order, as swept by scripts/harvest-globs.mjs. */
const optionNames = (header.get("options") ?? "").split("\t");

const OPTION_KEYS: Record<string, keyof GlobOptions> = {
  extendedglob: "extendedGlob",
  kshglob: "kshGlob",
  shglob: "shGlob",
  globdots: "globDots",
  bareglobqual: "bareGlobQual",
};

function optionsFor(combo: number): GlobOptions {
  const options: GlobOptions = { nullGlob: true };
  for (const [bit, name] of optionNames.entries()) {
    const key = OPTION_KEYS[name];
    if (!key) throw new Error(`unknown option in fixture: ${name}`);
    (options as Record<string, unknown>)[key] = ((combo >> bit) & 1) === 1;
  }
  return options;
}

/**
 * A leading `~` would be filename expansion, which happens only at the start
 * of a word; the harness prefixes a sentinel so `~` stays the operator it is
 * in the pattern, and the same rule applies here.
 */
const TILDE_SENTINEL = "Z";
const globFor = (glob: string) => (glob.startsWith("~") ? TILDE_SENTINEL + glob : glob);

const describeCombo = (combo: number) =>
  optionNames.map((n, bit) => (((combo >> bit) & 1) === 1 ? n : `no${n}`)).join(" ");

/** One distinct outcome, with the option combinations that produce it. */
const cases = lines
  .filter((line) => !line.startsWith("#") && line.length > 0)
  .map((line) => {
    const [maskText, index, results = ""] = line.split("\t");
    const glob = globTexts[Number(index) - 1];
    const rejected = maskText.endsWith("!");
    const body = rejected ? maskText.slice(0, -1) : maskText;
    // A `j` marks results that had to be JSON encoded: they name a file whose
    // bytes are not all characters.
    // `p` marks a word zsh did not glob, where the two differ only in whether
    // the backslashes survive; `j` marks JSON encoded results.
    const passthrough = body.endsWith("p");
    const afterP = passthrough ? body.slice(0, -1) : body;
    const jsonEncoded = afterP.endsWith("j");
    const mask = BigInt(`0x${jsonEncoded ? afterP.slice(0, -1) : afterP}`);
    const combos: number[] = [];
    for (let bit = 0; bit < 1 << optionNames.length; bit++) {
      if ((mask >> BigInt(bit)) & 1n) combos.push(bit);
    }
    return {
      rejected,
      passthrough,
      combos,
      glob,
      expected: jsonEncoded
        ? (JSON.parse(results) as string[]).filter((entry) => entry !== "")
        : results.split(SEPARATOR).filter((entry) => entry !== ""),
    };
  });

/**
 * Every glob in the corpus is now checked under every option combination.
 *
 * Two entries used to sit here.  `(#a1)(a#b)(a#b)Y` went when the matcher
 * gained the `exactpos`/`exactend` carry-over that decides it, and
 * `_?(*[^~])` went when glob qualifier subscripts stopped being read as
 * numbers: a subscript is an arithmetic expression, so `[^~]` is an error
 * rather than an index of zero.  See src/arith.ts.
 */
const KNOWN_DIVERGENCES = new Set<string>();

/**
 * The fixture is generated by expanding `${~use}`, because that is the only
 * way to sweep thousands of words programmatically.  For one shape that route
 * answers a different question from the one this package is asked.
 *
 * `zshtokenize` skips `<` when SH_GLOB is set, so through `${~use}` the word
 * never gains an `Inang` and `haswilds` calls it an ordinary word.  The lexer
 * tokenizes it either way, so a word written out is a pattern -- and
 * `haswilds` has no SH_GLOB test for `Inang` in the first place, running
 * "before zpc_special has been set up".  Written out, zsh agrees with this
 * package:
 *
 *   % zsh -f -c 'cd /tmp/gt; setopt shglob nullglob; m=( a<1-10> ); print [${(j:,:)m}]'
 *   []
 *   % zsh -f -c 'cd /tmp/gt; setopt shglob nullglob; p="a<1-10>"; m=( ${~p} ); print [${(j:,:)m}]'
 *   [a<1-10>]
 *
 * This package resolves backslash quoting, which `${~var}` does not, so it is
 * the written-out form it models throughout -- see the backslash tests in
 * glob.test.ts.  These rows record the other form, and are checked against the
 * written-out one instead.
 */
const SH_GLOB_RANGE = /<\d*-\d*>/;

function corpusRouteDiffers(glob: string, combo: number): boolean {
  return SH_GLOB_RANGE.test(glob) && /(^| )shglob( |$)/.test(describeCombo(combo));
}

let tree: string;

/** Rebuilds exactly the tree the fixture records, so results are comparable. */
beforeAll(() => {
  tree = mkdtempSync(join(tmpdir(), "zsh-globs-"));
  const at = (path: string) => join(tree, path);
  for (const dir of entries("treedirs")) mkdirSync(at(dir), { recursive: true });
  for (const file of entries("treefiles")) {
    mkdirSync(dirname(at(file)), { recursive: true });
    writeFileSync(at(file), file === "big" ? "x".repeat(2000) : file === "small" ? "aaaa" : "");
  }
  for (const link of entries("treelinks")) {
    trySymlink(link === "linkdir" ? "dir1" : "nowhere", at(link));
  }
  // The few attributes the fixture cannot carry: a mode, a FIFO and an old
  // timestamp, matching what scripts/harvest-globs.mjs sets up.
  if (existsSync(at("exec.sh"))) chmodSync(at("exec.sh"), 0o755);
  if (existsSync(at("noperm"))) chmodSync(at("noperm"), 0o000);
  if (existsSync(at("old.txt"))) {
    const old = new Date("2000-01-01T00:00:00Z");
    utimesSync(at("old.txt"), old, old);
  }
  if (canFifo) {
    rmSync(at("fifo"), { force: true });
    execFileSync("mkfifo", [at("fifo")]);
  }
});

afterAll(() => rmSync(tree, { recursive: true, force: true }));

/**
 * Whether a recorded result names the FIFO, in any form a glob can produce it:
 * bare, under a directory, and with the type character LIST_TYPES appends.  A
 * case like this cannot be judged on a host with no `mkfifo`, because the tree
 * it was captured from is not the tree we are able to build.
 */
const FIFO_ENTRY = /(^|\/)fifo[|@=*%/]?$/;
function needsFifo(expected: string[]): boolean {
  return expected.some((entry) => FIFO_ENTRY.test(entry));
}

// The recorded tree has symlinks in it, and the expected results were
// captured from that tree, so there is nothing to compare against on a host
// that cannot make one.
describe.skipIf(!canSymlink)("globs harvested from zsh's test suite", () => {
  it(`has a corpus, expanded by zsh ${zshVersion}`, () => {
    expect(optionNames.length).toBeGreaterThan(3);
    expect(entries("treefiles").length).toBeGreaterThan(500);
    expect(globTexts.length).toBeGreaterThan(3000);
    expect(cases.every((c) => typeof c.glob === "string")).toBe(true);
    const pairs = cases.reduce((sum, c) => sum + c.combos.length, 0);
    expect(pairs).toBeGreaterThan(90_000);
  });

  for (const { rejected, passthrough, combos, glob, expected } of cases) {
    const label = `${glob} (${combos.length} combination${combos.length === 1 ? "" : "s"})`;
    if (rejected) {
      // zsh refused this glob under these options, so the port must too.
      it.skipIf(KNOWN_DIVERGENCES.has(glob))(`${label} is rejected`, () => {
        for (const combo of combos) {
          expect(() => globSync(globFor(glob), { ...optionsFor(combo), cwd: tree })).toThrow(
            ZshPatternError,
          );
        }
      });
      continue;
    }
    // `Y` short circuits in directory traversal order, which differs between
    // two separately created trees, so only the number of matches is stable.
    const countOnly = /\(#?q?[^)]*Y\d/.test(glob);
    it.skipIf(KNOWN_DIVERGENCES.has(glob) || (!canFifo && needsFifo(expected)))(label, () => {
      for (const combo of combos) {
        let actual: string[];
        try {
          actual = globSync(globFor(glob), { ...optionsFor(combo), cwd: tree });
        } catch (err) {
          expect.fail(`${glob} under ${describeCombo(combo)}: ${(err as Error).message}`);
        }
        if (corpusRouteDiffers(glob, combo)) {
          // A pattern that spells only itself, so it matches nothing.
          expect(actual, `${glob} under ${describeCombo(combo)}`).toEqual([]);
        } else if (countOnly) {
          expect(actual, describeCombo(combo)).toHaveLength(expected.length);
        } else if (passthrough) {
          // The word was not globbed.  zsh keeps its backslashes and this
          // package resolves them, so what is compared is the word itself.
          const strip = (s: string) => s.replace(/\\/g, "");
          expect(actual, `${glob} under ${describeCombo(combo)}`).toHaveLength(1);
          expect(strip(actual[0]), `${glob} under ${describeCombo(combo)}`).toBe(
            strip(expected[0]),
          );
        } else {
          expect(actual, `${glob} under ${describeCombo(combo)}`).toEqual(expected);
        }
      }
    });
  }
});
