/**
 * Emits a zsh script that brace-expands an exhaustive corpus of short words,
 * so the real shell decides what each one produces.
 *
 *     node scripts/harvest-braces.mjs > /tmp/zg-braces.zsh
 *     zsh -f /tmp/zg-braces.zsh > test/fixtures/braces.txt
 *
 * The alphabet is chosen so that every structural decision in `hasbraces` and
 * `xpandbraces` is reachable: the braces themselves, the comma that makes a
 * list, the `..` that makes a range, a digit and a letter to range between,
 * and the `-` that signs a number and separates a BRACE_CCL range.  Every word
 * over it up to six characters is tried, which is enough to nest a group
 * inside another and still close both.
 *
 * Nothing here is quoted -- quoting would stop the expansion being tested --
 * so the alphabet must hold no character the shell would act on, and each word
 * is wrapped in a `Q` the reader strips back off.  Escaping is covered by hand in test/braces.test.ts instead,
 * because a backslash means something subtly different on either side: zsh
 * removes it during quote removal, while this package leaves it in place for
 * the globber to resolve later.
 */
export const ALPHABET = ["{", "}", ",", ".", "-", "a", "1"];
export const MAX_LENGTH = 5;

/** Every word over the alphabet, shortest first. */
function* words() {
  let level = [""];
  for (let n = 1; n <= MAX_LENGTH; n++) {
    const next = [];
    for (const prefix of level) {
      for (const ch of ALPHABET) {
        next.push(prefix + ch);
      }
    }
    yield* next;
    level = next;
  }
}

/**
 * A handful of longer words, past what the sweep reaches: three-number ranges,
 * wider padding, and a group nested two deep.
 */
export const EXTRA = [
  "{1..10}", "{1..10..3}", "{10..1..3}", "{01..10}", "{1..010}", "{1..10..02}",
  "{-5..5..2}", "{5..-5..2}", "{2..-2..2}", "{1..10..0}", "{1..1}", "{0..0}",
  "{a..z}", "{z..a}", "{A..z}", "{a..e..2}", "{9..11}", "{08..11}",
  "x{a,b}y{c,d}z", "{a,{b,c},d}", "{a{b,c}d}", "{{a,b},{c,d}}", "a{b{c,d}e}f",
  "{a,b}{c,d}{e,f}", "{,a}", "{a,,b}", "{,}", "{}", "{a}", "{a,b", "a,b}",
  "{-1..1}", "{1..-1}", "{0001..3}", "{100..1..25}", "{a-c}", "{a-cx-z}",
];

/** The corpus, shared with test/braces.test.ts so the two cannot drift. */
export function corpus() {
  return [...words(), ...EXTRA];
}

const all = corpus();

// Only write the script when run directly; the test imports the corpus.
if (process.argv[1] && process.argv[1].endsWith("harvest-braces.mjs")) {

const out = [];
out.push("# generated by scripts/harvest-braces.mjs -- do not edit");
out.push("emulate -R zsh");
out.push("setopt nonomatch noglob");
out.push(`print -r -- '#zsh\t'$ZSH_VERSION`);
// Each option setting is swept separately: braceccl changes which words
// expand at all, and ignorebraces turns the whole thing off.
for (const [name, setup] of [
  ["default", "unsetopt braceccl ignorebraces"],
  ["braceccl", "setopt braceccl; unsetopt ignorebraces"],
  ["ignorebraces", "unsetopt braceccl; setopt ignorebraces"],
]) {
  out.push(setup);
  for (const word of all) {
    // The index lets the reader pair a block of output with its word, and
    // the count makes an empty expansion unambiguous.
    out.push(`print -r -- '#word\t${name}\t'${JSON.stringify(word)}`);
    // Into an array first, so an empty expansion still shows as a word, and
    // a result starting with `-` is never read as an option.  The `Q` on each
    // end keeps the word from ever being a bare `{` or `}`, which the shell
    // reads as a reserved word; brace expansion is indifferent to text either
    // side of a group, so the answer is unchanged.
    out.push(`w=( Q${word}Q )`);
    out.push(`print -rl -- "\${(@)w/#/=}"`);
  }
}
process.stdout.write(out.join("\n") + "\n");
}
