/**
 * Turns the output of `scripts/harvest-approx.mjs` (run through zsh) into
 * `test/fixtures/approx.txt`, and refreshes the list of cases where this
 * package and zsh disagree.
 *
 * The zsh script echoes back the pattern and subject it actually tested, so
 * the answers are matched to their cases by content rather than by trusting
 * that the two arrays stayed in step.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { match } from "../dist/index.js";

const raw = readFileSync(process.argv[2], "utf8")
  .split("\n")
  .filter((line) => line.length > 0)
  .map((line) => {
    const [res, pattern, subject = ""] = line.split("\t");
    return { res, pattern, subject };
  });

const corpus = fileURLToPath(new URL("../test/fixtures/approx.txt", import.meta.url));
writeFileSync(
  corpus,
  [
    "# res\tpattern\tsubject  -- generated by scripts/harvest-approx.mjs, answers from ./zsh",
    ...raw.map((r) => `${r.res}\t${r.pattern}\t${r.subject}`),
  ].join("\n") + "\n",
);

/** What this package says: "t", "f", or "E" when it rejects the pattern. */
const ours = (r) => {
  try {
    return match(r.subject, r.pattern, { extendedGlob: true }) ? "t" : "f";
  } catch {
    return "E";
  }
};

const diverge = raw.filter((r) => ours(r) !== r.res);
writeFileSync(
  fileURLToPath(new URL("../test/fixtures/approx-divergences.txt", import.meta.url)),
  [
    "# pattern\tsubject -- cases where this port and zsh disagree under (#a).",
    "# Generated by comparing test/fixtures/approx.txt with this package;",
    "# test/approx.test.ts fails if the set changes in either direction.",
    ...diverge.map((r) => `${r.pattern}\t${r.subject}`),
  ].join("\n") + "\n",
);

process.stderr.write(`${raw.length} cases, ${diverge.length} divergences\n`);
